### PR TITLE
Update harbour-jupii-es.ts

### PR DESCRIPTION
**Pull request by GNUuser**

### CODE REVIEW

**Comment by GNUuser** [comment]
can you update languages files?

**Comment by mkiol** [comment]
Promise I will update them but I'm still doing changes that have impact on the translations. I want to make sure that everything is fixed and will not change.

**Comment by GNUuser** [comment]
ok sound good.

**Comment by mkiol** [comment]
Translation files for 2.2.x release are updated. I'm not planning any changes before final (=not beta) release. I would be grateful for your contribution!

**Pull request merged**
