### PR TITLE
Update harbour-jupii-es.ts

### PR DESCRIPTION
**Pull request by GNUuser**
I did  a translation BUT it seems that all *.ts files need a refresh.

### CODE REVIEW

**Comment by mkiol** [comment]
Yes indeed, TS files are not refreshed. I'm working on new release and many literals are in very not-polished state.

**Comment by mkiol** [comment]
Thank you for the update

**Comment by GNUuser** [comment]
I need check my translation after refreshing the TS files. I need perfect the spanish translation before Jupii release. :  )
Thank you for Juppi one of the best app to SAILFISH.

**Comment by mkiol** [comment]
> Thank you for Juppi one of the best app to SAILFISH

Ooo! Thank you for your generous comment :D

**Pull request merged**
